spring:
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema/schema.sql

logging:
  level:
    com.lovely4k.backend.authentication: debug
    com.lovely4k.backend.common.config: debug

love:
  met: se