spring:
  profiles:
    active: local   # 기본 환경
    include: credential # 비밀 정보들 관리 관련 yaml

# local
---
spring:
  config:
    activate:
      on-profile: local

# prod
---
spring:
  config:
    activate:
      on-profile: prod1

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod2

server:
  port: 8082
