spring:
  profiles:
    active: local   # 기본 환경
    include: credential # 비밀 정보들 관리 관련 yaml

# == 공통 설정 영역 == #
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
# prod
---
spring:
  config:
    activate:
      on-profile: prod1

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod2

server:
  port: 8082
