name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: team05-lovely-bucket

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build With Gradle
      run: ./gradlew clean build

    - name: Make Directory
      run: mkdir -p deploy

    - name: Copy Jar
      run: cp ./api/build/libs/*.jar ./deploy

    - name: Make zip file
      run: zip -r ./deploy.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # 서울 region

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://$S3_BUCKET_NAME/
